/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BookView: typeof import('./src/components/BookView.vue')['default']
    BPagination: typeof import('bootstrap-vue-next')['BPagination']
    copy: typeof import('./src/components/Index copy.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    IndexPage: typeof import('./src/components/IndexPage.vue')['default']
    IndexView: typeof import('./src/components/IndexView.vue')['default']
    IndexWrapper: typeof import('./src/components/IndexWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
