/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BookView: typeof import('./src/components/BookView.vue')['default']
    BPagination: typeof import('bootstrap-vue-next')['BPagination']
    IndexDetailsView: typeof import('./src/components/IndexDetailsView.vue')['default']
    IndexFilter: typeof import('./src/components/IndexFilter.vue')['default']
    IndexPagination: typeof import('./src/components/IndexPagination.vue')['default']
    IndexView: typeof import('./src/components/IndexView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
